### ISSUE TITLE
模块运行报错

### ISSUE THREAD

**Issue by landseer-ge** [linguishi/lstm-sentiment#27]
main.py 文件中第72行和第73行    embeddings = tf.nn.embedding_lookup(w2v_var, word_ids)
nn.embedding_lookup有个模块已经停用了，如果在cpu上跑不会返回零tesor会报错。请问该怎么办呢？
InvalidArgumentError (see above for traceback): indices[18,130] = 21492 is not in [0, 3621)
         [[node embedding_lookup (defined at main.py:73)  = GatherV2[Taxis=DT_INT32, Tindices=DT_INT64, Tparams=DT_FLOAT, _device="/
job:localhost/replica:0/task:0/device:CPU:0"](Variable/read, string_to_index_Lookup, embedding_lookup/axis)]]

**Comment by landseer-ge** [comment]
Using config: {'_model_dir': 'results/model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, 
'_save_checkpoints_secs': 60, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_dev
ice_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <te
nsorflow.python.training.server_lib.ClusterSpec object at 0x000002B84023D160>, '_task_type': 'worker', '_task_id': 0, '_global_id_in
_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
Not using Distribute Coordinator.
Running training and evaluation locally (non-distributed).
Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfi
g arguments: save_checkpoints_steps None or save_checkpoints_secs 60.
Calling model_fn.
Done calling model_fn.
Create CheckpointSaverHook.
Graph was finalized.
Restoring parameters from results/model\model.ckpt-0
Running local_init_op.
Done running local_init_op.
Saving checkpoints for 0 into results/model\model.ckpt.
Traceback (most recent call last):
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn        
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessio
nrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[6,90] = 21492 is not in [0, 3621)
         [[{{node embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT64, Tparams=DT_FLOAT, _device="/job:localhost/replica
:0/task:0/device:CPU:0"](Variable/read, string_to_index_Lookup, embedding_lookup/axis)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 158, in <module>
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\training.py", line 471, in train_and_ev
aluate
    return executor.run()
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\training.py", line 610, in run
    return self.run_local()
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\training.py", line 711, in run_local   
    saving_listeners=saving_listeners)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\estimator.py", line 354, in train      
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1207, in _train_mod
el
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1241, in _train_mod
el_default
    saving_listeners)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1471, in _train_wit
h_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\training\monitored_session.py", line 671, in run 
    run_metadata=run_metadata)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run        
    run_metadata)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call       
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[6,90] = 21492 is not in [0, 3621)
         [[node embedding_lookup (defined at main.py:73)  = GatherV2[Taxis=DT_INT32, Tindices=DT_INT64, Tparams=DT_FLOAT, _device="/
job:localhost/replica:0/task:0/device:CPU:0"](Variable/read, string_to_index_Lookup, embedding_lookup/axis)]]

Caused by op 'embedding_lookup', defined at:
  File "main.py", line 158, in <module>
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\training.py", line 471, in train_and_ev
aluate
    return executor.run()
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\training.py", line 610, in run
    return self.run_local()
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\training.py", line 711, in run_local   
    saving_listeners=saving_listeners)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\estimator.py", line 354, in train      
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1207, in _train_mod
el
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1237, in _train_mod
el_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1195, in _call_mode
l_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "main.py", line 73, in model_fn
    embeddings = tf.nn.embedding_lookup(w2v_var, word_ids,max_norm=None, name=None)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\ops\embedding_ops.py", line 313, in embedding_loo
kup
    transform_fn=None)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\ops\embedding_ops.py", line 133, in _embedding_lo
okup_and_transform
    result = _clip(array_ops.gather(params[0], ids, name=name),
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2675, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3331, in gather_v2   
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply
_op_helper
    op_def=op_def)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func      
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op       
    op_def=op_def)
  File "D:\anaconda3\envs\A_sentiment_analysis\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__        
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[6,90] = 21492 is not in [0, 3621)
         [[node embedding_lookup (defined at main.py:73)  = GatherV2[Taxis=DT_INT32, Tindices=DT_INT64, Tparams=DT_FLOAT, _device="/
job:localhost/replica:0/task:0/device:CPU:0"](Variable/read, string_to_index_Lookup, embedding_lookup/axis)]]

**Comment by linguishi** [comment]
这。。你用什么版本的tensorflow

**Comment by landseer-ge** [comment]
目前用的是‘1.12.0’，之前用‘1.13.1’也会报同样的错。

**Comment by landseer-ge** [comment]
embeddings = tf.nn.embedding_lookup(w2v_var, word_ids)每次报错都是这个函数。这次是用tensorflow‘1.13.1’的结果
InvalidArgumentError (see above for traceback): indices[12,254] = 21492 is not in [0, 3621)
         [[node embedding_lookup (defined at main.py:84) ]]
