### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by KyleLeith-007** [linguishi/lstm-sentiment#30]
Traceback (most recent call last):
  File "···/chinese_sentiment-master/data/hotel_comment/raw_data/fix_coupus.py", line 30, in <module>
    fix_corpus(POS, FIX_POS)
  File "···/chinese_sentiment-master/data/hotel_comment/raw_data/fix_coupus.py", line 15, in fix_corpus
    fix_s = s.decode('gb2312')
AttributeError: 'str' object has no attribute 'decode'
代码如下：
def fix_corpus(dir_s, dir_t):
    for item in os.listdir(dir_s):
        with open(os.path.join(dir_s, item), 'r',) as f:
            try:
                s = f.read()
                fix_s = s.decode('gb2312')
            except UnicodeDecodeError:
                try:
                    fix_s = s.decode('gbk')
                except UnicodeDecodeError:
                    fix_s = s.decode('gb2312', errors='ignore')
            with codecs.open(os.path.join(dir_t, item), 'w', encoding='utf8') as ff:
                ff.write(fix_s)

**Comment by zzzendurance** [comment]
你这个最后搞好了吗？

**Comment by KyleLeith-007** [comment]
> 你这个最后搞好了吗？

我换了个项目，不过你可以重写这个转换编码函数，参考这个：https://blog.csdn.net/juluwangriyue/article/details/109053440

**Comment by HEMXX2** [comment]
> 你这个最后搞好了吗？
请问你解决了这个问题吗？

**Comment by wxtrsrzrcj** [comment]
> Traceback (most recent call last): File "···/chinese_sentiment-master/data/hotel_comment/raw_data/fix_coupus.py", line 30, in fix_corpus(POS, FIX_POS) File "···/chinese_sentiment-master/data/hotel_comment/raw_data/fix_coupus.py", line 15, in fix_corpus fix_s = s.decode('gb2312') AttributeError: 'str' object has no attribute 'decode' 代码如下： def fix_corpus(dir_s, dir_t): for item in os.listdir(dir_s): with open(os.path.join(dir_s, item), 'r',) as f: try: s = f.read() fix_s = s.decode('gb2312') except UnicodeDecodeError: try: fix_s = s.decode('gbk') except UnicodeDecodeError: fix_s = s.decode('gb2312', errors='ignore') with codecs.open(os.path.join(dir_t, item), 'w', encoding='utf8') as ff: ff.write(fix_s)

open里面打开文件的方式将‘r'改为’rb‘，二进制才能decode

**Comment by KyleLeith-007** [comment]
非常感谢，已经解决了。



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 20, 2024 21:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [linguishi/chinese_sentiment] AttributeError: 'str' object has noattribute 'decode' (Issue #30)




  
Traceback (most recent call last): File "···/chinese_sentiment-master/data/hotel_comment/raw_data/fix_coupus.py", line 30, in fix_corpus(POS, FIX_POS) File "···/chinese_sentiment-master/data/hotel_comment/raw_data/fix_coupus.py", line 15, in fix_corpus fix_s = s.decode('gb2312') AttributeError: 'str' object has no attribute 'decode' 代码如下： def fix_corpus(dir_s, dir_t): for item in os.listdir(dir_s): with open(os.path.join(dir_s, item), 'r',) as f: try: s = f.read() fix_s = s.decode('gb2312') except UnicodeDecodeError: try: fix_s = s.decode('gbk') except UnicodeDecodeError: fix_s = s.decode('gb2312', errors='ignore') with codecs.open(os.path.join(dir_t, item), 'w', encoding='utf8') as ff: ff.write(fix_s)
  
open里面打开文件的方式将‘r'改为’rb‘，二进制才能decode
